{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legal-backend.fullname" . }}-secret
  labels:
    {{- include "legal-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  # API Keys
  {{- if and .Values.openai .Values.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.mongodb .Values.mongodb.password }}
  MONGO_PASSWORD: {{ .Values.mongodb.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  # JWT Secret
  {{- if and .Values.auth .Values.auth.jwtSecret }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | b64enc | quote }}
  {{- end }}
{{- end }}
