# argocd-manifests/apps/loki.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    # Chạy ở Wave 0, cùng lúc với Prometheus, PostgreSQL...
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tinhnguyen0110/LexiOps.git' # <-- URL Repo của bạn
    targetRevision: main
    path: 'helm'
    # Dùng plugin helmfile thông minh của chúng ta
    plugin:
      name: helmfile
      env:
        - name: HELM_SELECTOR
          value: "app=loki"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]