apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: legal-backend-external-secret
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: legal-secret-store
  target:
    name: legal-backend-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Database Secrets
        MONGO_PASSWORD: "{{ .mongo_password }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
        
        # API Keys
        OPENAI_API_KEY: "{{ .openai_api_key }}"
        
        # Authentication
        JWT_SECRET: "{{ .jwt_secret }}"
        
        # Additional secrets
        SECRET_KEY: "{{ .secret_key }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        
  data:
    - secretKey: mongo_password
      remoteRef:
        key: mongodb-credentials
        property: password
        
    - secretKey: redis_password
      remoteRef:
        key: redis-credentials
        property: password
        
    - secretKey: openai_api_key
      remoteRef:
        key: openai-credentials
        property: api_key
        
    - secretKey: jwt_secret
      remoteRef:
        key: auth-secrets
        property: jwt_secret
        
    - secretKey: secret_key
      remoteRef:
        key: auth-secrets
        property: secret_key
        
    - secretKey: encryption_key
      remoteRef:
        key: auth-secrets
        property: encryption_key
