{{- if .Values.baseSecrets.enabled }}
---
# Namespace application
apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    purpose: application-workloads

---
# Backend Secret - chứa tất cả environment variables cho backend
apiVersion: v1
kind: Secret
metadata:
  name: legal-backend-secret
  namespace: application
  labels:
    app.kubernetes.io/name: legal-backend
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: legal-retrieval
type: Opaque
stringData:
  # Database Configuration
  MONGO_USERNAME: "legal_user"
  MONGO_PASSWORD: "{{ .Values.baseSecrets.mongodb.password }}"
  REDIS_PASSWORD: "{{ .Values.baseSecrets.redis.password }}"
  
  # API Keys
  OPENAI_API_KEY: "{{ .Values.baseSecrets.openai.apiKey }}"
  
  # Authentication & Security
  JWT_SECRET: "{{ .Values.baseSecrets.auth.jwtSecret }}"
  SECRET_KEY: "{{ .Values.baseSecrets.auth.secretKey }}"
  ENCRYPTION_KEY: "{{ .Values.baseSecrets.auth.encryptionKey }}"

---
# Frontend Secret - chứa environment variables cho React frontend
apiVersion: v1
kind: Secret
metadata:
  name: legal-frontend-secret
  namespace: application
  labels:
    app.kubernetes.io/name: legal-frontend
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: legal-retrieval
type: Opaque
stringData:
  # Frontend Configuration
  REACT_APP_API_BASE_URL: "{{ .Values.baseSecrets.frontend.apiBaseUrl }}"
  REACT_APP_GOOGLE_ANALYTICS_ID: "{{ .Values.baseSecrets.analytics.gaTrackingId }}"
  REACT_APP_ENABLE_ANALYTICS: "{{ .Values.baseSecrets.analytics.enableAnalytics }}"

---
# Celery Worker Secret - chứa environment variables cho Celery worker
apiVersion: v1
kind: Secret
metadata:
  name: legal-celery-worker-secret
  namespace: application
  labels:
    app.kubernetes.io/name: legal-celery-worker
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: legal-retrieval
type: Opaque
stringData:
  # Database Configuration (giống backend)
  MONGO_USERNAME: "legal_user"
  MONGO_PASSWORD: "{{ .Values.baseSecrets.mongodb.password }}"
  REDIS_PASSWORD: "{{ .Values.baseSecrets.redis.password }}"
  
  # API Keys
  OPENAI_API_KEY: "{{ .Values.baseSecrets.openai.apiKey }}"
  
  # Celery Configuration
  CELERY_BROKER_PASSWORD: "{{ .Values.baseSecrets.redis.password }}"
  CELERY_RESULT_BACKEND_PASSWORD: "{{ .Values.baseSecrets.redis.password }}"
  
  # Security
  SECRET_KEY: "{{ .Values.baseSecrets.auth.secretKey }}"
{{- end }}
