apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: legal-celery-worker-external-secret
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: legal-secret-store
  target:
    name: legal-celery-worker-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Database Secrets
        MONGO_PASSWORD: "{{ .mongo_password }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
        
        # API Keys
        OPENAI_API_KEY: "{{ .openai_api_key }}"
        
        # Celery Configuration
        CELERY_BROKER_PASSWORD: "{{ .redis_password }}"
        CELERY_RESULT_BACKEND_PASSWORD: "{{ .redis_password }}"
        
        # Additional secrets
        SECRET_KEY: "{{ .secret_key }}"
        
  data:
    - secretKey: mongo_password
      remoteRef:
        key: mongodb-credentials
        property: password
        
    - secretKey: redis_password
      remoteRef:
        key: redis-credentials
        property: password
        
    - secretKey: openai_api_key
      remoteRef:
        key: openai-credentials
        property: api_key
        
    - secretKey: secret_key
      remoteRef:
        key: auth-secrets
        property: secret_key
