# Simple Kubernetes Secret Store for Development
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    kubernetes:
      # For Kind cluster, use the internal service account of the ESO itself
      remoteNamespace: {{ .Values.secretStore.remoteNamespace }}
      auth:
        serviceAccount:
          name: setup-secrets-external-secrets
          namespace: secrets-store
      server:
        # Use cluster internal CA
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: secrets-store
        url: https://kubernetes.default.svc

---
# Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.secretStore.remoteNamespace }}
  labels:
    purpose: secrets-storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-management

---
# Service Accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: secrets-management

---
# RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-reader
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: secrets-management