# Simple Kubernetes Secret Store for Development
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.secretStore.remoteNamespace }}
      auth:
        serviceAccount:
          name: external-secrets-sa

---
# Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.secretStore.remoteNamespace }}
  labels:
    purpose: secrets-storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-management

---
# Service Accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: {{ .Values.secretStore.namespace }}

---
# RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-reader
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: {{ .Values.secretStore.namespace }}