{{- if .Values.externalSecrets.backend.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legal-backend-external-secret
  namespace: application
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.backend.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.backend.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.externalSecrets.backend.remoteSecretName }}
      property: {{ . }}
  {{- end }}
{{- end }}
---
{{- if .Values.externalSecrets.frontend.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legal-frontend-external-secret
  namespace: application
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.frontend.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.frontend.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.externalSecrets.frontend.remoteSecretName }}
      property: {{ . }}
  {{- end }}
{{- end }}
---
{{- if .Values.externalSecrets.celeryWorker.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: legal-celery-worker-external-secret
  namespace: application
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.celeryWorker.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.celeryWorker.keys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.externalSecrets.celeryWorker.remoteSecretName }}
      property: {{ . }}
  {{- end }}
{{- end }}
