apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: legal-frontend-external-secret
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: legal-secret-store
  target:
    name: legal-frontend-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # API Configuration
        REACT_APP_API_BASE_URL: "{{ .api_base_url }}"
        
        # Authentication
        REACT_APP_JWT_SECRET: "{{ .jwt_secret }}"
        
        # Analytics/Tracking (if needed)
        REACT_APP_GOOGLE_ANALYTICS_ID: "{{ .ga_tracking_id }}"
        
        # Feature flags
        REACT_APP_ENABLE_ANALYTICS: "{{ .enable_analytics }}"
        
  data:
    - secretKey: api_base_url
      remoteRef:
        key: frontend-config
        property: api_base_url
        
    - secretKey: jwt_secret
      remoteRef:
        key: auth-secrets
        property: jwt_secret
        
    - secretKey: ga_tracking_id
      remoteRef:
        key: analytics-config
        property: ga_tracking_id
        
    - secretKey: enable_analytics
      remoteRef:
        key: analytics-config
        property: enable_analytics

---
# Additional secrets for frontend in secrets-management namespace
apiVersion: v1
kind: Secret
metadata:
  name: frontend-config
  namespace: secrets-management
type: Opaque
stringData:
  api_base_url: "https://api.legal-retrieval.yourdomain.com"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-config
  namespace: secrets-management
type: Opaque
stringData:
  ga_tracking_id: "GA-XXXXXXXX-X"
  enable_analytics: "false"
