# Secret Store để tham chiếu secrets từ secrets-store namespace
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    kubernetes:
      # Reference to secrets in secrets-store namespace
      remoteNamespace: {{ .Values.secretStore.remoteNamespace }}
      server:
        # Use in-cluster config
        caProvider:
          type: "ConfigMap"
          name: "kube-root-ca.crt"
          key: "ca.crt"
      auth:
        serviceAccount:
          name: {{ .Values.rbac.serviceAccountName | default "external-secrets-sa" }}
