# Values for celery worker - link type
# This worker handles link analysis and extraction tasks

workerType: link

image:
  repository: legal-chatbot-backend
  tag: dns-fix-v1
  pullPolicy: Never

worker:
  name: "celery-worker-link"
  concurrency: 2
  queues: "link_queue"
  logLevel: "INFO"

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

env:
  APP_NAME: "Legal Link Worker"
  WORKER_TYPE: "link"
  CELERY_QUEUES: "link_queue"
