# Legal Celery Worker - Simplified Configuration (Production-like)
# ==============================================================

image:
  repository: legal-retrieval/backend
  tag: "latest"
  pullPolicy: Never

replicaCount: 1

env:
  DOCKER_ENV: "true"
  APP_NAME: "Legal Retrieval Worker"
  DEBUG: "true"
  LOG_LEVEL: "INFO"
  
  # Database connections (matching docker-compose)
  MONGO_URL: "mongodb://admin:password123@legal-mongodb:27017/legaldb?authSource=admin"
  REDIS_URL: "redis://legal-redis:6379/0"
  REDIS_URL_WS: "redis://legal-redis:6379/1"
  REDIS_URL_RETRIEVAL: "redis://legal-redis:6379/2"
  QDRANT_URL: "http://legal-qdrant:6333"
  
  # Celery configuration
  CELERY_BROKER_URL: "redis://legal-redis:6379/3"
  CELERY_RESULT_BACKEND: "redis://legal-redis:6379/4"
  CELERY_QUEUES: "rag_queue,embed_queue,retrieval_queue,link_extract_queue"
  CELERY_CONCURRENCY: "2"
  CELERY_LOGLEVEL: "info"
  CELERY_POOL: "eventlet"
