# Values for celery worker - rag type
# This worker handles RAG (Retrieval Augmented Generation) tasks

workerType: rag

image:
  repository: legal-chatbot-backend
  tag: dns-fix-v1
  pullPolicy: Never

worker:
  name: "celery-worker-rag"
  concurrency: 2
  queues: "rag_queue"
  logLevel: "INFO"

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

env:
  APP_NAME: "Legal RAG Worker"
  WORKER_TYPE: "rag"
  CELERY_QUEUES: "rag_queue"
