# MongoDB - SIMPLE Configuration for Development Testing
# ====================================================

# Disable auth cho simple testing (no password needed)
auth:
  enabled: false
  
# Use standalone architecture
architecture: standalone

# Disable persistence for testing (in-memory)
persistence:
  enabled: false

# Simple service
service:
  type: ClusterIP
  port: 27017

# Minimal resources để tránh resource issues
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi" 
    cpu: "200m"

# Disable tất cả complex features
metrics:
  enabled: false
  serviceMonitor:
    enabled: false

replicaSet:
  enabled: false

# Simple security context
podSecurityContext:
  enabled: false

# No custom configuration
configuration: ""

# No init scripts để tránh lỗi
initdbScripts: {}

# Arbiter (disabled)
arbiter:
  enabled: false
