# 🔧 External Secrets Configuration for Legal Retrieval
# =====================================================
# Chỉ tạo SecretStore + ExternalSecrets (operator đã cài riêng)

# RBAC cho External Secrets
rbac:
  enabled: true
  # ServiceAccount name sẽ được tạo trong application namespace
  serviceAccountName: external-secrets-sa

# Secret Store - tham chiếu tới secrets-store namespace
secretStore:
  name: legal-secret-store
  namespace: application
  remoteNamespace: secrets-store
  
# External Secret configurations
externalSecrets:
  backend:
    enabled: true
    secretName: legal-backend-secret
    remoteSecretName: legal-backend-secret
    keys:
      - MONGO_PASSWORD
      - OPENAI_API_KEY  
      - JWT_SECRET
      - REDIS_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SENTRY_DSN
      
  frontend:
    enabled: true
    secretName: legal-frontend-secret
    remoteSecretName: legal-frontend-secret
    keys:
      - VITE_API_KEY
      - VITE_APP_SECRET
      - VITE_GOOGLE_ANALYTICS_ID
      
  celeryWorker:
    enabled: true
    secretName: legal-celery-worker-secret
    remoteSecretName: legal-celery-worker-secret
    keys:
      - MONGO_PASSWORD
      - OPENAI_API_KEY
      - JWT_SECRET
      - REDIS_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SENTRY_DSN
