# 🏭 Production External Secrets Configuration
# =============================================
# For production deployment with real external secret stores

# External Secrets Operator (sẽ cài khi production)
externalSecretsOperator:
  enabled: false  # Disable cho development
  namespace: external-secrets-system
  version: "0.9.11"

# RBAC cho External Secrets  
rbac:
  enabled: false  # Disable cho development
  serviceAccountName: external-secrets-sa

# Secret Store Configuration (Production only)
secretStore:
  enabled: false  # Enable khi production
  name: legal-secret-store
  namespace: application
  provider: aws  # aws | vault | azure | gcp
  
  # AWS Secrets Manager configuration
  aws:
    region: "us-west-2"
    auth:
      secretRef:
        accessKeyID:
          name: aws-credentials
          key: access-key-id
        secretAccessKey:
          name: aws-credentials  
          key: secret-access-key

  # HashiCorp Vault configuration (alternative)
  vault:
    server: "https://vault.company.com"
    path: "secret"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "legal-app"

# External Secret configurations (Production)
externalSecrets:
  enabled: false  # Enable khi production
  
  backend:
    enabled: true
    secretName: legal-backend-secret
    # AWS Secrets Manager paths
    aws:
      secretKey: "legal/backend"
    # Or Vault paths  
    vault:
      path: "secret/legal/backend"
    keys:
      - MONGO_PASSWORD
      - OPENAI_API_KEY
      - JWT_SECRET
      - REDIS_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SENTRY_DSN
      
  frontend:
    enabled: true
    secretName: legal-frontend-secret
    aws:
      secretKey: "legal/frontend"
    vault:
      path: "secret/legal/frontend"
    keys:
      - NEXT_PUBLIC_API_URL
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      
  celeryWorker:
    enabled: true
    secretName: legal-celery-worker-secret
    aws:
      secretKey: "legal/celery"
    vault:
      path: "secret/legal/celery"
    keys:
      - MONGO_PASSWORD
      - OPENAI_API_KEY
      - JWT_SECRET
      - REDIS_PASSWORD
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
      - SENTRY_DSN

# Migration strategy
migration:
  # Steps to migrate from direct secrets to External Secrets:
  # 1. Deploy External Secrets Operator
  # 2. Setup AWS Secrets Manager / Vault
  # 3. Upload secrets to external store
  # 4. Enable externalSecrets.enabled: true
  # 5. Deploy ExternalSecrets resources
  # 6. Verify sync working
  # 7. Remove direct secrets
