# 🔧 Simple External Secrets Setup
# ================================

# External Secrets Operator
external-secrets:
  enabled: true
  installCRDs: true
  replicaCount: 1
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Secret Store - using Kubernetes (simple setup)
secretStore:
  name: legal-secret-store
  namespace: application
  remoteNamespace: secrets-store

# External Secret configurations
externalSecrets:
  backend:
    enabled: true
  frontend:
    enabled: true
  celeryWorker:
    enabled: true

# RBAC
rbac:
  enabled: true
