# Default values for legal-backend chart

# Component type: api or celery-worker
component: api

# Image configuration
image:
  repository: legal-retrieval/backend
  tag: "latest"
  pullPolicy: IfNotPresent

# Replica configuration
replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 8000

# Environment variables (NON-SECRET only, secrets từ legal-secrets secret)
env:
  # Application settings
  APP_NAME: "Legal Backend API"
  ENVIRONMENT: "development"
  DEBUG: "true"
  LOG_LEVEL: "INFO"
  API_V1_STR: "/api"
  HOST: "0.0.0.0"
  PORT: "8000"
  
  # Database connections (non-secret parts)
  MONGODB_HOST: "legal-mongodb.data-service.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "legal_retrieval"
  MONGODB_USERNAME: "legal_user"
  MONGO_URL: "mongodb://legal_user:$(MONGO_PASSWORD)@legal-mongodb.data-service.svc.cluster.local:27017/legal_retrieval"
  
  # Redis connection (non-secret part)
  REDIS_HOST: "legal-redis.data-service.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@legal-redis.data-service.svc.cluster.local:6379/0"
  REDIS_URL_WS: "redis://:$(REDIS_PASSWORD)@legal-redis.data-service.svc.cluster.local:6379/1"
  REDIS_URL_RETRIEVAL: "redis://:$(REDIS_PASSWORD)@legal-redis.data-service.svc.cluster.local:6379/2"
  
  # Vector database
  QDRANT_HOST: "legal-qdrant.data-service.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_URL: "http://legal-qdrant.data-service.svc.cluster.local:6333"
  
  # Celery configuration (using secret ref)
  CELERY_BROKER_URL: "redis://:$(REDIS_PASSWORD)@legal-redis.data-service.svc.cluster.local:6379/0"
  CELERY_RESULT_BACKEND: "redis://:$(REDIS_PASSWORD)@legal-redis.data-service.svc.cluster.local:6379/0"
  
  # Feature flags
  ENABLE_ANALYTICS: "false"
  ENABLE_MONITORING: "true"

# Celery worker specific configuration
worker:
  type: rag
  queues: "rag_queue,embed_queue"
  concurrency: 2
  logLevel: INFO

# Resource configuration
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Autoscaling configuration (disabled for development)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

# Health check configuration
healthCheck:
  enabled: true
  path: "/health"
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: "/ready"
  initialDelaySeconds: 5
  periodSeconds: 5

# Security context - container level
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL

# Security context - pod level
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: api.legal-retrieval.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Auth configuration
auth:
  jwtSecret: ""

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  requestLogging: true

# Model configuration
model:
  embedding: "sentence-transformers/all-MiniLM-L6-v2"
  llm: "gpt-3.5-turbo"

# Performance configuration
performance:
  maxConcurrentRequests: 10
  requestTimeout: 300
  workerThreads: 1

# Database connections
mongodb:
  host: "localhost"
  port: "27017"
  database: "legal_db"
  url: ""
  username: ""
  password: ""

redis:
  host: "localhost"
  port: "6379"
  url: ""
  password: ""

qdrant:
  host: "localhost"
  port: "6333"
  url: ""

# OpenAI configuration
openai:
  apiKey: ""

# Secrets configuration
secrets:
  enabled: true
  secretName: "legal-secrets"  # Single shared secret với sensitive data
  createSecret: false  # Disable creating individual secret, use shared secret instead