apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "legal-celery-worker.fullname" . }}-config
  labels:
    {{- include "legal-celery-worker.labels" . | nindent 4 }}
data:
  # Worker configuration
  CELERY_WORKER_TYPE: {{ .Values.worker.type | quote }}
  CELERY_QUEUES: {{ .Values.worker.queues | quote }}
  CELERY_CONCURRENCY: {{ .Values.worker.concurrency | quote }}
  CELERY_LOG_LEVEL: {{ .Values.worker.logLevel | quote }}
  CELERY_MAX_TASKS_PER_CHILD: {{ .Values.worker.maxTasksPerChild | quote }}
  CELERY_PREFETCH_MULTIPLIER: {{ .Values.worker.prefetchMultiplier | quote }}
  CELERY_POOL: {{ .Values.worker.pool | quote }}
