apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Gán vào wave 0, chạy đầu tiên
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tinhnguyen0110/LexiOps'
    targetRevision: main
    path: 'helm'
    plugin:
      name: helmfile
      env:
        - name: HELM_SELECTOR
          value: "app=legal-backend"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true