apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "legal-frontend.fullname" . }}-config
  labels:
    {{- include "legal-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  
  # Vite environment variables
  VITE_API_BASE_URL: {{ .Values.config.apiBaseUrl | quote }}
  VITE_API_TIMEOUT: {{ .Values.config.apiTimeout | quote }}
  VITE_APP_TITLE: {{ .Values.config.appTitle | quote }}
  VITE_APP_DESCRIPTION: {{ .Values.config.appDescription | quote }}
  VITE_APP_VERSION: {{ .Chart.AppVersion | quote }}
  
  # Feature flags
  VITE_ENABLE_CHAT: {{ .Values.config.enableChat | quote }}
  VITE_ENABLE_DOCUMENT_SEARCH: {{ .Values.config.enableDocumentSearch | quote }}
  VITE_ENABLE_HISTORY: {{ .Values.config.enableHistory | quote }}
  
  # UI configuration
  VITE_THEME: {{ .Values.config.theme | quote }}
  VITE_LANGUAGE: {{ .Values.config.language | quote }}
  VITE_MAX_CHAT_HISTORY: {{ .Values.config.maxChatHistory | quote }}
  
  # Performance settings
  VITE_DEBOUNCE_DELAY: {{ .Values.config.debounceDelay | quote }}
  VITE_CHUNK_SIZE: {{ .Values.config.chunkSize | quote }}
