{{- if and .Values.secrets (gt (len .Values.secrets) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legal-frontend.fullname" . }}-secret
  labels:
    {{- include "legal-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
