# External Secrets Operator configuration
external-secrets:
  enabled: true
  installCRDs: true
  
  replicaCount: 2
  
  # Security context
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    
  # Resource limits
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

# Environment configuration (development, staging, production)
environment: development

# Secret Store selection based on environment
secretStore:
  # Provider type: kubernetes, aws, azure, gcp
  provider: kubernetes
  
  # Kubernetes provider config (for development)
  kubernetes:
    enabled: true
    name: legal-secret-store
    namespace: application
    remoteNamespace: secrets-store  # Can be replaced with cloud provider
    
  # AWS Secrets Manager config (for production)  
  aws:
    enabled: false
    name: aws-secret-store
    region: us-west-2
    
  # Azure Key Vault config
  azure:
    enabled: false
    name: azure-secret-store
    vaultUrl: ""
    
  # Google Secret Manager config
  gcp:
    enabled: false
    name: gcp-secret-store
    projectId: ""

# Namespaces
namespaces:
  # Secrets storage (replace with cloud provider in production)
  secretsStore: secrets-store
  # External Secrets Operator management
  management: secrets-management
  # Application namespace  
  application: application

# Base secrets configuration (for development environment)
baseSecrets:
  enabled: true
  
  mongodb:
    username: legaluser
    password: legal-mongo-dev-password-123
    
  redis:
    password: legal-redis-dev-password-123
    
  openai:
    apiKey: sk-your-openai-api-key-here-replace-in-production
    
  auth:
    jwtSecret: legal-jwt-super-secret-key-development-only
    secretKey: legal-app-secret-key-development-change-in-prod
    encryptionKey: legal-32-char-encryption-dev-key-12
    
  frontend:
    apiBaseUrl: http://legal-backend-api.application.svc.cluster.local:8000
    
  analytics:
    gaTrackingId: GA-DEVELOPMENT-ID
    enableAnalytics: false

# External Secret configurations
externalSecrets:
  backend:
    enabled: true
    name: legal-backend-external-secret
    namespace: application
    
  frontend:
    enabled: true
    name: legal-frontend-external-secret
    namespace: application
    
  celeryWorker:
    enabled: true
    name: legal-celery-worker-external-secret
    namespace: application

# RBAC configuration
rbac:
  enabled: true
  serviceAccount:
    name: external-secrets-sa
    namespace: application
