# Simple setup-secrets chart for Legal Retrieval
# Values được cập nhật từ .env file

# Environment configuration
environment: development

# Namespaces
namespaces:
  application: application

# Base secrets configuration từ .env file
baseSecrets:
  enabled: true
  
  mongodb:
    username: legal_user
    password: "legal_password"
    
  redis:
    password: "legal-redis-dev-password-123"
    
  openai:
    apiKey: "test_api_key"
  auth:
    jwtSecret: "legal-jwt-super-secret-key-development"
    secretKey: "dev_secret_key_change_in_production"
    encryptionKey: "legal-32-char-encryption-dev-key"
    
  frontend:
    apiBaseUrl: "http://legal-backend-api.application.svc.cluster.local:8000"
    
  analytics:
    gaTrackingId: "GA-DEVELOPMENT-ID"
    enableAnalytics: false

# ConfigMaps configuration
configMaps:
  enabled: true
  
  # Backend configuration
  backend:
    environment: "development"
    debug: true
    logLevel: "DEBUG"
    
  # Frontend configuration  
  frontend:
    nodeEnv: "development"
    theme: "light"
    language: "vi"
    
  # Celery configuration
  celery:
    workerType: "general"
    logLevel: "INFO"
    concurrency: 2
