# Default values for legal-celery-worker chart

# Image configuration
image:
  repository: legal-chatbot-backend
  tag: "dns-fix-v1"
  pullPolicy: Never

# Deployment configuration
replicaCount: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

# Worker-specific configuration (will be overridden by individual values files)
worker:
  type: "rag"
  queues: "rag_queue"
  concurrency: 2
  logLevel: INFO
  maxTasksPerChild: 1000
  prefetchMultiplier: 1
  pool: "eventlet"

# Environment variables (NON-SECRET only, secrets từ legal-secrets secret)
env:
  # Application settings
  APP_NAME: "Legal Celery Worker"
  ENVIRONMENT: "development"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # Celery configuration (will be overridden by individual values files)
  CELERY_WORKER_TYPE: "rag"
  CELERY_QUEUES: "rag_queue"
  CELERY_CONCURRENCY: "2"
  CELERY_LOG_LEVEL: "INFO"
  CELERY_MAX_TASKS_PER_CHILD: "1000"
  CELERY_PREFETCH_MULTIPLIER: "1"
  CELERY_POOL: "eventlet"
  
  # Database connections (non-secret parts)
  MONGODB_HOST: "legal-mongodb.data-service.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "legal_retrieval"
  MONGODB_USERNAME: "legal_user"
  MONGO_URL: "mongodb://legal_user:$(MONGO_PASSWORD)@legal-mongodb.data-service.svc.cluster.local:27017/legal_retrieval"
  
  # Redis connections  
  REDIS_HOST: "legal-redis-master.data-service.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  # CELERY URLs loaded from legal-secrets
  
  # Vector database
  QDRANT_HOST: "legal-qdrant.data-service.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_URL: "http://legal-qdrant.data-service.svc.cluster.local:6333"

# Environment variables from ConfigMaps and Secrets
envFrom:
  # Sensitive data từ shared secret
  - secretRef:
      name: legal-secrets

# Secrets configuration
secrets:
  enabled: true
  secretName: "legal-secrets"  # Single shared secret với sensitive data

# Legacy database connections (overridden by secrets)
legacyEnv:
  # Database connections (will be overridden in values)
  MONGO_URL: "mongodb://localhost:27017/legaldb"
  REDIS_URL: "redis://localhost:6379/0"
  QDRANT_URL: "http://localhost:6333"

# Resource configuration
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Liveness probe for Celery worker
livenessProbe:
  enabled: true
  exec:
    command:
      - /bin/sh
      - -c
      - "celery -A app.celery_worker inspect ping -d celery@$HOSTNAME"
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Volume configuration
volumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}

volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: cache
    mountPath: /app/cache

# Node selector and scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "false"

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Termination grace period
terminationGracePeriodSeconds: 60

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Network policy
networkPolicy:
  enabled: false
